# Look for the different tagged releases at:
# https://hub.docker.com/r/library/python/tags/

stages:
    - test

test2.7:
  image: "python:2.7"
  stage: test
  variables:
    PYVER: "2.7"
  before_script:
    - python --version  # Print out version for debugging
  script:
    - make shippable_test

test3.4:
  image: "python:3.4"
  stage: test
  variables:
    PYVER: "3.4"
  before_script:
    - python --version  # Print out version for debugging
  script:
    - make shippable_test

test3.5:
  image: "python:3.5"
  stage: test
  variables:
    PYVER: "3.5"
  before_script:
    - python --version  # Print out version for debugging
  script:
    - make shippable_test

test3.6:
  image: "python:3.6"
  stage: test
  variables:
    PYVER: "3.6"
  before_script:
    - python --version  # Print out version for debugging
  script:
    - make shippable_test
